# Generated by Django 3.1.5 on 2021-02-25 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='num_people_followed',
        ),
    ]
