# Generated by Django 3.1.5 on 2021-02-25 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_remove_user_num_people_followed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='num_people_followed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
