# Generated by Django 3.1.5 on 2021-01-31 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_remove_user_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='biddings',
            new_name='bidding',
        ),
    ]
