# Generated by Django 3.1.5 on 2021-02-01 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210201_0554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='listing',
            new_name='w_listing',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='user',
            new_name='w_user',
        ),
    ]
