# Generated by Django 3.1.5 on 2021-02-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='winner',
            field=models.CharField(default='Null', max_length=230),
        ),
    ]
